#!/usr/bin/env node

/**
 * generate-version.mjs
 *
 * Reads the version from the root package.json and writes
 * packages/shared/src/generated-version.ts so that the shared package
 * (and everything importing APP_VERSION) uses a single source of truth.
 *
 * This script is run automatically before `tsc -b` in the shared package
 * via the "prebuild" lifecycle hook.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const pkgPath = join(root, "package.json");
const outPath = join(root, "packages/shared/src/generated-version.ts");

// Read version from root package.json
let version;
try {
  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  version = pkg.version;
} catch (err) {
  console.error("generate-version: failed to read root package.json", err);
  process.exit(1);
}

if (!version || typeof version !== "string") {
  console.error("generate-version: root package.json has no valid version field");
  process.exit(1);
}

// Write the generated TS file
const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually.
// Single source of truth: root package.json version "${version}".
export const APP_VERSION = "${version}";
`;

writeFileSync(outPath, content, "utf-8");
console.log(`generate-version: wrote APP_VERSION = "${version}" → ${outPath}`);
